kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster

# Create 3 control-plane and 3 worker nodes
nodes:
  - role: control-plane

  - role: control-plane

  - role: control-plane

  - role: worker

  - role: worker

  - role: worker

# Configure containerd mirrors (equivalent to k3d registries)
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["http://172.17.0.1:5000"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
        endpoint = ["http://172.17.0.1:5001"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
        endpoint = ["http://172.17.0.1:5003"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io"]
        endpoint = ["http://172.17.0.1:5002"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.k8s.io"]
        endpoint = ["http://172.17.0.1:5004"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."cr.l5d.io"]
        endpoint = ["http://172.17.0.1:5005"]
